---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Stop and disable Netbird service
  ansible.builtin.service:
    name: "{{ netbird_service_name }}"
    state: stopped
    enabled: false
  ignore_errors: true
  become: true

- name: Kill Netbird process
  ansible.builtin.command: pkill netbird
  ignore_errors: true
  become: true

- name: Remove Netbird package (Debian)
  ansible.builtin.apt:
    name: netbird
    state: absent
  when: netbird_install_method == 'deb'
  become: true

- name: Remove Netbird repository (Debian)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/netbird-archive-keyring.gpg] https://pkgs.netbird.io/debian stable main"
    state: absent
  when: netbird_install_method == 'deb'
  become: true

- name: Remove Netbird GPG key (Debian)
  ansible.builtin.file:
    path: /usr/share/keyrings/netbird-archive-keyring.gpg
    state: absent
  when: netbird_install_method == 'deb'
  become: true

- name: Remove Netbird package (RedHat)
  ansible.builtin.yum:
    name: netbird
    state: absent
  when: netbird_install_method == 'rpm'
  become: true

- name: Remove Netbird repository (RedHat)
  ansible.builtin.yum_repository:
    name: netbird
    state: absent
  when: netbird_install_method == 'rpm'
  become: true

- name: Remove Netbird package (Arch)
  community.general.pacman:
    name: netbird
    state: absent
  when: netbird_install_method == 'pacman'
  become: true

- name: Uninstall Netbird service (Binary)
  ansible.builtin.command:
    cmd: "{{ netbird_binary_install_dir }}/netbird service uninstall"
  ignore_errors: true
  when: netbird_install_method == 'binary'
  become: true

- name: Remove Netbird service file (Binary)
  ansible.builtin.file:
    path: /etc/systemd/system/netbird.service
    state: absent
  when: netbird_install_method == 'binary'
  become: true

- name: Remove Netbird binary (Binary)
  ansible.builtin.file:
    path: "{{ netbird_binary_install_dir }}/netbird"
    state: absent
  when: netbird_install_method == 'binary'
  become: true

- name: Final kill of Netbird process
  ansible.builtin.command: pkill netbird
  ignore_errors: true
  become: true
