---
- name: Create temporary download directory
  ansible.builtin.file:
    path: /tmp/netbird-install
    state: directory
    mode: '0755'

- name: Download and unarchive Netbird
  ansible.builtin.unarchive:
    src: "https://github.com/netbirdio/netbird/releases/download/v{{ netbird_version }}/netbird_{{ netbird_version }}_linux_{{ netbird_arch }}.tar.gz"
    dest: /tmp/netbird-install
    remote_src: true
    creates: /tmp/netbird-install/netbird

- name: Install Netbird binary
  ansible.builtin.copy:
    src: /tmp/netbird-install/netbird
    dest: "{{ netbird_binary_install_dir }}/netbird"
    mode: '0755'
    owner: root
    group: root
    remote_src: true
  notify: restart netbird
  become: true

- name: Install Netbird service
  ansible.builtin.command:
    cmd: "{{ netbird_binary_install_dir }}/netbird service install"
    creates: /etc/systemd/system/netbird.service
  become: true

- name: Start Netbird service
  ansible.builtin.service:
    name: netbird
    state: started
    enabled: true
  become: true

- name: Cleanup temporary directory
  ansible.builtin.file:
    path: /tmp/netbird-install
    state: absent
