---
- name: Add Netbird repository
  ansible.builtin.yum_repository:
    name: netbird
    description: Netbird
    baseurl: https://pkgs.netbird.io/yum/
    enabled: true
    gpgcheck: false
    repo_gpgcheck: true
    gpgkey: https://pkgs.netbird.io/yum/repodata/repomd.xml.key
  register: netbird_repo_rpm
  become: true

- name: Install Netbird
  ansible.builtin.yum:
    name: netbird
    state: "{{ netbird_state }}"
    update_cache: "{{ netbird_state == 'latest' or netbird_repo_rpm.changed }}"
  notify: restart netbird
  become: true
