---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - procps
    state: present
    update_cache: true
  become: true

- name: Add Netbird repository
  ansible.builtin.deb822_repository:
    name: netbird
    types: deb
    uris: https://pkgs.netbird.io/debian
    suites: stable
    components: main
    signed_by: https://pkgs.netbird.io/debian/public.key
    state: present
    install_python_debian: true
  become: true

- name: Install Netbird
  ansible.builtin.apt:
    name: netbird
    state: "{{ netbird_state }}"
    update_cache: "{{ netbird_state == 'latest' }}"
  notify: restart netbird
  become: true
