---
- name: Install dependencies
  community.general.pacman:
    name:
      - base-devel
      - ca-certificates
      - git
      - go
    state: present
  become: true

- name: Create build user
  ansible.builtin.user:
    name: netbird-builder
    create_home: true
    shell: /bin/bash
  become: true

- name: Clone Netbird AUR repository
  ansible.builtin.git:
    repo: https://aur.archlinux.org/netbird.git
    dest: /home/netbird-builder/netbird
    update: true
  become: true
  become_user: netbird-builder
  environment:
    GIT_SSL_NO_VERIFY: "true"

- name: Build Netbird package
  ansible.builtin.command:
    cmd: makepkg -f --noconfirm
    chdir: /home/netbird-builder/netbird
  become: true
  become_user: netbird-builder
  changed_when: true

- name: Find built package
  ansible.builtin.find:
    paths: /home/netbird-builder/netbird
    patterns: "*.pkg.tar.zst"
  register: built_package
  become: true

- name: Install Netbird package
  community.general.pacman:
    name: "{{ built_package.files[0].path }}"
    state: present
  become: true
  notify: restart netbird

- name: Remove build user
  ansible.builtin.user:
    name: netbird-builder
    state: absent
    remove: true
  become: true
