---
- name: Add Netbird repository
  ansible.builtin.yum_repository:
    name: netbird
    description: Netbird
    baseurl: https://pkgs.netbird.io/yum/
    enabled: true
    gpgcheck: false
    repo_gpgcheck: true
    gpgkey: https://pkgs.netbird.io/yum/repodata/repomd.xml.key

- name: Install Netbird
  ansible.builtin.yum:
    name: netbird
    state: present
  notify: restart netbird
