---
- name: Handle absent state
  ansible.builtin.include_tasks: absent.yml
  when: netbird_state == 'absent'

- name: Perform installation
  when: netbird_state == 'present'
  block:
    - name: Include OS-specific installation tasks
      ansible.builtin.include_tasks: "install-{{ netbird_install_method }}.yml"

    - name: Ensure Netbird service is running
      ansible.builtin.service:
        name: "{{ netbird_service_name }}"
        state: started
        enabled: true
      become: true
