---
- name: Converge
  hosts: all
  tasks:
    - name: Include netbird role (absent)
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        netbird_state: absent
