---
- name: Prepare
  hosts: all
  tasks:
    - name: Include netbird role (present)
      ansible.builtin.include_role:
        # See: https://github.com/ansible/molecule/issues/1567#issuecomment-436876722
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        netbird_state: present
        netbird_version: "{{ '0.30.5' if netbird_install_method | default('deb') == 'binary' else omit }}"
