---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if binary exists
      ansible.builtin.command: which netbird
      register: binary_check
      ignore_errors: true
      changed_when: false
      failed_when: binary_check.rc == 0

    - name: Check if service is loaded (netbird.service)
      ansible.builtin.systemd:
        name: netbird
      register: service_status
      failed_when: service_status.status.LoadState != 'not-found'

    - name: Check if service is loaded (netbird@main.service)
      ansible.builtin.systemd:
        name: netbird@main
      register: service_status
      failed_when: service_status.status.LoadState != 'not-found'
