---
- name: restart netbird
  ansible.builtin.service:
    name: "{{ netbird_service_name }}"
    state: restarted
    enabled: true
  become: true

- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
