---
- name: Converge
  hosts: all
  tasks:
    - name: Include netbird role
      ansible.builtin.include_role:
        # See: https://github.com/ansible/molecule/issues/1567#issuecomment-436876722
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
