---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Set netbird service name
      ansible.builtin.set_fact:
        netbird_service_name: "{{ 'netbird@main' if ansible_facts['os_family'] == 'Archlinux' else 'netbird' }}"

    - name: Check for netbird service running
      ansible.builtin.command: systemctl is-active {{ netbird_service_name }}
      changed_when: false
