---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Check for netbird service running
      ansible.builtin.command: systemctl is-active netbird
      changed_when: false
